# -*- coding: utf-8 -*-
"""Untitled120.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iPd263GrE6DC26ah3TvY_COhRPrwAumK

TEAM MEMBERS:-

Priyanka Boral(MT19127)


Reecha Kumari Giri(MT19134)


Akanksha Dewangan(MT19049)

Loding data:
"""

#loading of test train data of amino acid+dipeptide
#label encoding of target column
import pandas as pd
df_train = pd.read_csv('Merged_Train_Data.csv')
df_test = pd.read_csv('Merged_Test_Data.csv')
del df_train['ID.1']
test_labels=df_test['ID.1']
del df_test['ID.1']
from sklearn import preprocessing  
#label encoding
label_encoder = preprocessing.LabelEncoder() 
df_train['Type']= label_encoder.fit_transform(df_train['Type'])
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
#print(label_mapping)
X = df_train.iloc[:,:-1]
y = df_train['Type']

"""Feature selection : select k best using f-ANNOVA

Model used : SVM classifier

Cross validation : 5-fold

Label encoding of target column form {0,1} to {1,-1}
"""

from sklearn.feature_selection import SelectKBest,f_classif
#feature selection
sel_f = SelectKBest(score_func=f_classif, k=215)
X_new = sel_f.fit_transform(X, y)
X_new_test=sel_f.transform(df_test)
#print(sel_f.get_support())
from sklearn import svm
svc_f = svm.SVC(kernel='rbf', C=3, gamma='scale',class_weight='balanced')
from sklearn.model_selection import train_test_split,KFold,cross_val_score
kfold = KFold(n_splits=5,shuffle=True)
#cross validation
results = cross_val_score(svc_f, X_new, y, cv=kfold)
print(results.mean())
svc_f.fit(X_new, y)
y_pred=svc_f.predict(X_new_test)
y_pred_temp_rf=[]
for i in y_pred:
   if i==0:
     y_pred_temp_rf.append(1)
   else:
     y_pred_temp_rf.append(-1)
 #copying to sample file
data_res=pd.DataFrame()
data_res['ID']=test_labels
data_res['Lable']=y_pred_temp_rf
data_res.to_csv (r'merged_featureselection_svm.csv', index = False,header=True)